name: KNIME-TemplateMatching
channels:
  - defaults
dependencies:
  - python=3.6          # Python
  - pandas=0.23         # Table data structures
  - jedi=0.13           # Python script autocompletion
  - python-dateutil=2.7 # Date and Time utilities
  - numpy=1.15          # N-dimensional arrays
  - cairo=1.14          # SVG support
  - pillow=5.3          # Image inputs/outputs
  - matplotlib=3.0      # Plotting
  - pyarrow=0.11        # Arrow serialization
  - IPython=7.1         # Notebook support
  - nbformat=4.4        # Notebook support
  - scipy=1.1           # Notebook support
  - scikit-image=0.14.2 # Local maxima detection
  - opencv=3.4.2        # matchTemplate

prefix: C:\Anaconda\envs\KNIME-TM
